import type { NextPage } from 'next'
import Head from 'next/head'
import { Slogan } from '../components/Slogan'
import Box from '@mui/material/Box'
import beach from '../assets/beach.jpg'
import Container from '@mui/material/Container'
import { WeatherCardsContainer } from '../components/WeatherCardsContainer/WeatherCardsContainer'
import { YourCityWeatherInput } from '../components/Input/YourCityWeatherInput'
import { AirportCityInput } from '../components/Input/AirportCityInput'
import { TypographySlogan } from '../components/Typography/TypographySlogan'
import { BaseButton } from '../components/Button/Button'
import { NumberInput } from '../components/Input/NumberInput'
import * as React from 'react'
import { ChoseWeatherInput } from '../components/Input/ChoseWeatherInput'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Vacation App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          height: 800,
          backgroundImage: `url(${beach.src})`,
          backgroundSize: 'cover',
          position: 'relative',
          display: 'flex',
          justifyContent: 'center',
          textAlign: 'center',
        }}
      >
        <Slogan />
        <Container
          sx={{
            position: 'absolute',
            mt: { xs: '45%', sm: '25%', md: '18%', lg: '12%' },
            backgroundColor: 'white',
            width: '85%',
            height: '70%',
            borderRadius: '10px',
          }}
        >
          <YourCityWeatherInput />
          <WeatherCardsContainer />
          <AirportCityInput />
          <TypographySlogan text={'Twoja wymarzona pogoda'} />
          <Box>
            <NumberInput />
            <span>&#8451;</span>
            <ChoseWeatherInput />
          </Box>
          <BaseButton
            variant={'contained'}
            sx={{
              width: '100%',
              fontSize: '18px',
              backgroundColor: '#1976d2',
              mt: '10px',
            }}
          >
            Szukaj
          </BaseButton>
        </Container>
      </Box>
    </>
  )
}
export default Home
