import type { NextPage } from 'next'
import Head from 'next/head'
import { Slogan } from '../components/Slogan'
import Box from '@mui/material/Box'
import beach from '../assets/beach.jpg'
import Container from '@mui/material/Container'
import { WeatherCardsContainer } from '../components/WeatherCardsContainer/WeatherCardsContainer'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Vacation App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          height: 800,
          backgroundImage: `url(${beach.src})`,
          backgroundSize: 'cover',
          position: 'relative',
          display: 'flex',
          justifyContent: 'center',
          textAlign: 'center',
        }}
      >
        <Slogan />
        <Container
          sx={{
            position: 'absolute',
            mt: { xs: '45%', sm: '25%', md: '18%', lg: '12%' },
            backgroundColor: 'white',
            width: '85%',
            height: '70%',
            borderRadius: '10px',
          }}
        >
          <WeatherCardsContainer />
        </Container>
      </Box>
    </>
  )
}
export default Home
